import pandas as pd
import math

def nw(s,t,mt,mmt,indel):
    snew = '$'+s
    tnew = '$'+t
    a = range(0,len(tnew))
    b = range(0,len(snew))
    df = pd.DataFrame(columns=a)
    df = df.astype(int)
    for i in b:
        if i%10 == 0:
            print(i)
        df = df.append(pd.DataFrame([[0]*len(a)],columns=a), ignore_index=True)
    v = df.astype(str)
    for j in a[1:]:
        df.loc[0,j] = indel*j
        v.loc[0,j] = '→'
    for i in b[1:]:
        df.loc[i,0] = indel*i
        v.loc[i,0] = '↓'
    count = 0
    for i in b[1:]:
        for j in a[1:]:
            count = count + 1
            zz = 100*(count/(len(b[1:])*len(a[1:])))
            if zz%10 == 0:
                print(zz)
            d1 = 0
            if snew[i] == tnew[j]:
                d1 = df.loc[i-1,j-1]+mt
            else:
                d1 = df.loc[i-1,j-1]+mmt
            d2 = df.loc[i,j-1] + indel
            d3 = df.loc[i-1,j] + indel
            l = [d1,d2,d3]
            if mt <= mmt or mt <= indel:
                df.loc[i,j] = min(l)
                if df.loc[i,j] == d1:
                    v.loc[i,j] = '↘'
                elif df.loc[i,j] == d2:
                    v.loc[i,j] = '→'
                else:
                    v.loc[i,j] = '↓'
            else:
                df.loc[i,j] = max(l)
                if df.loc[i,j] == d1:
                    v.loc[i,j] = '↘'
                elif df.loc[i,j] == d2:
                    v.loc[i,j] = '→'
                else:
                    v.loc[i,j] = '↓'
    o1, o2 = rec_nw(v,snew,tnew)
    return o1, o2

def rec_nw(v,snew,tnew):
    #snew = '$'+s
    #tnew = '$'+t
    out1 = ''
    out2 = ''
    i = v.shape[0] -1
    j = v.shape[1] -1
    while i != 0 and j != 0:
        if v.loc[i,j] == '→':
            out2 = tnew[j] + out2
            out1 = '-' + out1
            j = j - 1
        elif v.loc[i,j] == '↓':
            out1 = snew[i] + out1
            out2 = '-' + out2
            i = i - 1
        else:
            out1 = snew[i] + out1
            out2 = tnew[j] + out2
            j = j - 1
            i = i - 1
    return out1, out2

s = 'GGCAGATTCCCCCTAGACCCGCCCGCACCATGGTCAGGCATGCCCCTCCTCATCGCTGGGCACAGCCCAGAGGGT\
ATAAACAGTGCTGGAGGCTGGCGGGGCAGGCCAGCTGAGTCCTGAGCAGCAGCCCAGCGCAGCCACCGAGACACC\
ATGAGAGCCCTCACACTCCTCGCCCTATTGGCCCTGGCCGCACTTTGCATCGCTGGCCAGGCAGGTGAGTGCCCC\
CACCTCCCCTCAGGCCGCATTGCAGTGGGGGCTGAGAGGAGGAAGCACCATGGCCCACCTCTTCTCACCCCTTTG\
GCTGGCAGTCCCTTTGCAGTCTAACCACCTTGTTGCAGGCTCAATCCATTTGCCCCAGCTCTGCCCTTGCAGAGG\
GAGAGGAGGGAAGAGCAAGCTGCCCGAGACGCAGGGGAAGGAGGATGAGGGCCCTGGGGATGAGCTGGGGTGAAC\
CAGGCTCCCTTTCCTTTGCAGGTGCGAAGCCCAGCGGTGCAGAGTCCAGCAAAGGTGCAGGTATGAGGATGGACC\
TGATGGGTTCCTGGACCCTCCCCTCTCACCCTGGTCCCTCAGTCTCATTCCCCCACTCCTGCCACCTCCTGTCTG\
GCCATCAGGAAGGCCAGCCTGCTCCCCACCTGATCCTCCCAAACCCAGAGCCACCTGATGCCTGCCCCTCTGCTC\
CACAGCCTTTGTGTCCAAGCAGGAGGGCAGCGAGGTAGTGAAGAGACCCAGGCGCTACCTGTATCAATGGCTGGG\
GTGAGAGAAAAGGCAGAGCTGGGCCAAGGCCCTGCCTCTCCGGGATGGTCTGTGGGGGAGCTGCAGCAGGGAGTG\
GCCTCTCTGGGTTGTGGTGGGGGTACAGGCAGCCTGCCCTGGTGGGCACCCTGGAGCCCCATGTGTAGGGAGAGG\
AGGGATGGGCATTTTGCACGGGGGCTGATGCCACCACGTCGGGTGTCTCAGAGCCCCAGTCCCCTACCCGGATCC\
CCTGGAGCCCAGGAGGGAGGTGTGTGAGCTCAATCCGGACTGTGACGAGTTGGCTGACCACATCGGCTTTCAGGA\
GGCCTATCGGCGCTTCTACGGCCCGGTCTAGGGTGTCGCTCTGCTGGCCTGGCCGGCAACCCCAGTTCTGCTCCT\
CTCCAGGCACCCTTCTTTCCTCTTCCCCTTGCCCTTGCCCTGACCTCCCAGCCCTATGGATGTGGGGTCCCCATC\
ATCCCAGCTGCTCCCAAATAAACTCCAGAAG'
t = 'CCACTGCACTCACCGCACCCGGCCAATTTTTGTGTTTTTAGTAGAGACTAAATACCATATAGTGAACACCTAAGA\
CGGGGGGCCTTGGATCCAGGGCGATTCAGAGGGCCCCGGTCGGAGCTGTCGGAGATTGAGCGCGCGCGGTCCCGG\
GATCTCCGACGAGGCCCTGGACCCCCGGGCGGCGAAGCTGCGGCGCGGCGCCCCCTGGAGGCCGCGGGACCCCTG\
GCCGGTCCGCGCAGGCGCAGCGGGGTCGCAGGGCGCGGCGGGTTCCAGCGCGGGGATGGCGCTGTCCGCGGAGGA\
CCGGGCGCTGGTGCGCGCCCTGTGGAAGAAGCTGGGCAGCAACGTCGGCGTCTACACGACAGAGGCCCTGGAAAG\
GTGCGGCAGGCTGGGCGCCCCCGCCCCCAGGGGCCCTCCCTCCCCAAGCCCCCCGGACGCGCCTCACCCACGTTC\
CTCTCGCAGGACCTTCCTGGCTTTCCCCGCCACGAAGACCTACTTCTCCCACCTGGACCTGAGCCCCGGCTCCTC\
ACAAGTCAGAGCCCACGGCCAGAAGGTGGCGGACGCGCTGAGCCTCGCCGTGGAGCGCCTGGACGACCTACCCCA\
CGCGCTGTCCGCGCTGAGCCACCTGCACGCGTGCCAGCTGCGAGTGGACCCGGCCAGCTTCCAGGTGAGCGGCTG\
CCGTGCTGGGCCCCTGTCCCCGGGAGGGCCCCGGCGGGGTGGGTGCGGGGGGCGTGCGGGGCGGGTGCAGGCGAG\
TGAGCCTTGAGCGCTCGCCGCAGCTCCTGGGCCACTGCCTGCTGGTAACCCTCGCCCGGCACTACCCCGGAGACT\
TCAGCCCCGCGCTGCAGGCGTCGCTGGACAAGTTCCTGAGCCACGTTATCTCGGCGCTGGTTTCCGAGTACCGCT\
GAACTGTGGGTGGGTGGCCGCGGGATCCCCAGGCGACCTTCCCCGTGTTTGAGTAAAGCCTCTCCCAGGAGCAGC\
CTTCTTGCCGTGCTCTCTCGAGGTCAGGACGCGAGAGGAAGGCGC'
o1, o2 = nw(s,t,0,3,1)
print(o2)
print(o1)
